on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true
      - run: echo "Version=${{ steps.nbgv.outputs.Version }}"
      - name: Pack
        run: dotnet pack ./BlockBasedMemoryStream/BlockBasedMemoryStream.csproj -o . -c Release /p:Version=${{ steps.nbgv.outputs.Version }}
      - name: Push
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json